VERSION 0.7

PROJECT earthly-sa/earthly-vs-gha

FROM ubuntu:23.10
WORKDIR /deploy
# RUN --secret MY_KEY=my_key echo $MY_KEY



RUN --secret TEST_SECRET=test_secret echo $TEST_SECRET
# earthly secret --org earthly-sa  --project earthly-vs-gha set fly_api_token YOUR_FLY_API_TOKEN
ENV --secret FLY_API_TOKEN=fly_api_token

deps:
    RUN apt update
    RUN apt install -y curl git
    RUN curl -L https://fly.io/install.sh | sh
    RUN /root/.fly/bin/flyctl --help

# only run this once
# fo1_NizaKkK-x01Ye7Q8FQt75BX9mWpgZ63X6YycJ0PEn5M
deploy-go:
    ARG --required tag
    FROM +deps
    DO +DEPLOY --name=earthly-go-example --org=earthly --image=ezeev/earthly-go-example --tag=$tag --port=8001

deploy-python:
    ARG --required tag
    FROM +deps
    DO +DEPLOY --name=earthly-python-example --org=earthly --image=ezeev/earthly-python-example --tag=$tag --port=8002

deploy-rust:
    ARG --required tag
    FROM +deps
    DO +DEPLOY --name=earthly-rust-example --org=earthly --image=ezeev/earthly-rust-example --tag=$tag --port=8000

deploy-node:
    ARG --required tag
    FROM +deps
    DO +DEPLOY --name=earthly-node-example --org=earthly --image=ezeev/earthly-node-example --tag=$tag --port=8003

deploy-front-end:
    ARG --required tag
    FROM +deps
    DO +DEPLOY --name=earthly-react-example --org=earthly --image=ezeev/earthly-react-example --tag=$tag --port=80

deploy-all:
    ARG --required tag
    BUILD +deploy-go --tag=$tag
    BUILD +deploy-python --tag=$tag
    BUILD +deploy-rust --tag=$tag
    BUILD +deploy-node --tag=$tag
    BUILD +deploy-front-end --tag=$tag

DEPLOY:
    COMMAND
    ARG name
    ARG org
    ARG image
    ARG tag
    ARG port
    RUN --no-cache if /root/.fly/bin/flyctl apps destroy -y $name | grep "Could not find"; then echo "App not found"; else echo "App found, recreating"; fi
    RUN --no-cache /root/.fly/bin/flyctl launch --image $image:$tag --internal-port $port --name $name --org $org --region lax 
    RUN --no-cache /root/.fly/bin/flyctl deploy