VERSION 0.8
PROJECT earthly-sa/earthly-vs-gha

FROM node:19.5.0-buster-slim 
WORKDIR /quote-client

deps:
  COPY --dir src index.html package.json tsconfig.json tsconfig.node.json postcss.config.cjs tailwind.config.cjs vite.config.ts yarn.lock .
  COPY --dir public .
  RUN yarn global add typescript
  RUN yarn

test:
  FROM +deps
  RUN ls public/
  RUN echo TODO: Implement react tests here

build:
  FROM +deps
  ARG --required go_server_url
  ARG --required rust_server_url
  ARG --required python_server_url
  ARG --required node_server_url
  RUN VITE_RUST_SERVER=$rust_server_url \
    VITE_GO_SERVER=$go_server_url \
    VITE_PYTHON_SERVER=$python_server_url \
    VITE_NODE_SERVER=$node_server_url \
    yarn build
  SAVE ARTIFACT dist/

docker:
  FROM nginx:latest 
  ARG tag=latest
  COPY +build/dist /usr/share/nginx/html/
  EXPOSE 80
  SAVE IMAGE --push idelvall/earthly-demo-react:$tag

deploy:
  ARG tag=latest
  BUILD ../infra+deploy --image=idelvall/earthly-demo-react --tag=$tag --port=80
  RUN echo "https://earthly-demo-react.fly.dev/">service
  SAVE ARTIFACT service service
